---
title: "Harvest Control Rules"
author: "Laurence Kell & Niels Hintzen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown:::html_document
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{kobe}
  \DeclareUnicodeCharacter{00A0}{ }
  %\VignetteEncoding{UTF-8}
bibliography: refs.bib
tags: FLPKG FLR
license: Creative Commons Attribution-ShareAlike 4.0 International
---

```{r, eval=TRUE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)

opts_chunk$set(comment=NA, 
               warning=FALSE, 
               message=FALSE, 
               error  =FALSE, 
               echo   =FALSE, 
               eval   =!TRUE,
               fig.width =4, 
               fig.height=4)

iFig=0
iTab=0
```

```{r init, eval=TRUE}
library(plyr)
library(ggplot2)
library(kobe)
library(reshape2)

dirMy="D:/Repository/DGMARETuna/tutorials/advice_framework"
dirMy="/home/laurie/Desktop/flr/tutorials/advice_framework"
dirTex=file.path(dirMy,"tex")
dirDat=file.path(dirMy,"data")

load(file.path(dirDat,"yft.RData"))

trk =transform(subset(yft,year%in%1970:2014),stock=stock,harvest=harvest)[,
                  c("year","Scenario","Method","stock","harvest")]
trk2=ddply(melt(trk,id=c("Scenario","Method","year")),.(variable,year,Method,Scenario),with, 
               median(value))
msy  =ddply(yft,.(Method,Scenario), with, c("bmsy"=bmsy[!is.na(bmsy)][1],"fmsy"=fmsy[!is.na(fmsy)][1]))

quads=rbind(data.frame(x=c(-Inf,-Inf,Inf,Inf), y=c(-Inf,  1,  1,-Inf), 
                         fill=as.factor("high")),
            data.frame(x=c(-Inf,-Inf,Inf,Inf), y=c(   1,Inf,Inf,   1), 
                         fill=as.factor("low")))
quad2=rbind(cbind(variable="stock",ddply(msy,.(Method,Scenario), 
                        transform, y=quads$y*bmsy,x=quads$x,fill=quads$fill)),
            cbind(variable="harvest",ddply(msy,.(Method,Scenario), 
                        transform, y=quads$y*fmsy,x=quads$x,fill=quads$fill)))[,-(4:5)]

quad2=transform(quad2,variable=ifelse(variable=="harvest","F/F[MSY]","B/B[MSY]"))

hcr= data.frame(stock  =c(0.0 ,0.1 , 0.6,7.5), 
                harvest=c(0.01,0.01, 0.7,0.7))
```


### Harvest control rule

```{r}
kobePhase()+
  geom_line(aes(stock,harvest),data=hcr,col="orange",size=2)
```

```{r, eval=TRUE}
kobePhase(dat)+
  geom_point(aes(stock,harvest),shape=21,fill="red",col="brown",size=1.0)+
  geom_point(aes(stock,harvest),shape=21,fill="red",col="brown",size=1.0)+  
  geom_line(aes(stock,harvest),data=hcr,col="orange",size=2)
```

```{r}
kobePhase(dat)+
  geom_point(aes(stock,harvest),shape=21,fill="red",col="brown",size=1.0,)+
  geom_point(aes(stock,harvest),shape=21,fill="red",col="brown",size=1.0)+  
  geom_line(aes(stock,harvest),data=hcr,col="orange",size=1)+
  facet_grid(Method~Scenario)
```


## Excercise

Based on shiny apps

### Project using a HCR

# References
